### PR TITLE
refactor/scala 3

### PR DESCRIPTION
**Pull request by cric96**
- build: move to scala 3.*; drop scala mock
- style: move to scala 3 code style
- build(02): move to scala 3
- style(02): prefer top level definition instead of extending App
- build(04): move to scala 3
- style(04): move to scala 3 code style

### CODE REVIEW

**Review by DanySK — CHANGES_REQUESTED** [review]

**Comment by DanySK** [comment]
Two minors. Let me know @cric96

**Review by cric96 — COMMENTED** [review]
Typos :) thanks!

**Comment by DanySK** [comment]
02 still uses scala 2 :)

**Comment by cric96** [comment]
Uhm no: 
https://github.com/cric96/PPS-ci-examples/blob/55a651ef8eb6dd21428d07ad980d08efca2fb938/02-multilang/build.gradle.kts#L13

**Comment by DanySK** [comment]
You're right. I can't understand why everything works in the mainline but it does not with this PR.

**Pull request merged**
